// Generated by accept-md. Do not edit the markdown block by hand.
import { getMarkdownForPath, loadConfig } from 'accept-md-runtime';

const cache = new Map();

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', 'GET');
    return res.status(405).end();
  }
  const path = req.query.path || '/';
  const config = loadConfig(process.cwd());
  const baseUrl = config.baseUrl || (req.headers.origin || req.headers.referer || '').replace(/\/?$/, '') || ('http://localhost:' + (process.env.PORT || 3000));
  try {
    const markdown = await getMarkdownForPath({
      pathname: path,
      baseUrl,
      config,
      cache: config.cache !== false ? cache : undefined,
    });
    res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
    if (config.cache) {
      res.setHeader('Cache-Control', 'public, s-maxage=60, stale-while-revalidate');
    }
    res.status(200).send(markdown);
  } catch (err) {
    res.status(500).json({
      error: err instanceof Error ? err.message : 'Markdown generation failed',
    });
  }
}
